### ISSUE TITLE
EXPRESIONES BOOLEANAS-YANET

### ISSUE THREAD

**Issue by yanet02** [SistemasTecTlaxiaco/expresiones-boolenas-eq-erick-yanet-lourdes-1as#1]
[Prácticade expresiones booleanas-Yanet.pdf](https://github.com/SistemasTecTlaxiaco/expresiones-boolenas-eq-erick-yanet-lourdes-1as/files/7730155/Practicade.expresiones.booleanas-Yanet.pdf)

**Comment by irving1613** [comment]
**Calificacion: 30%**
El trabajo esta bien hecho de manera completa. Incluyendo la explicacion de cada uno de los temas, de manera clara y precisa.
Cumple tambien con la explicacion paso a paso de cada uno de los ejercicios a realizar.

**Comment by josealfredo79** [comment]
Bien hecho y revisado
