### ISSUE TITLE
Expresiones booleanas-Maria de lourdes

### ISSUE THREAD

**Issue by lourdeshernandez2003** [SistemasTecTlaxiaco/expresiones-boolenas-eq-erick-yanet-lourdes-1as#2]
[Prácticade expresiones booleanas-Maria de Lourdes Hernandez.pdf](https://github.com/SistemasTecTlaxiaco/expresiones-boolenas-eq-erick-yanet-lourdes-1as/files/7731855/Practicade.expresiones.booleanas-Maria.de.Lourdes.Hernandez.pdf)

**Comment by 71santiago7** [comment]
Calificación: 30%   excelente trabajo  viene  todo   lo que pide  la rubrica

**Comment by josealfredo79** [comment]
Bien hecho y revisado
